disabled_rules: # rule identifiers turned on by default to exclude from running
- trailing_whitespace
- vertical_whitespace
- function_body_length
- cyclomatic_complexity
- type_body_length
- computed_accessors_order
- colon
- identifier_name
- comment_spacing

line_length:
- 200 # warning
- 300 # error

force_cast: warning
