disabled_rules: # rule identifiers turned on by default to exclude from running
- trailing_whitespace
- vertical_whitespace

identifier_name:
  min_length: 2 # only min_length

line_length:
- 200 # warning
- 300 # error
